if [[ -z $TMUX ]]; then
    export TERM='xterm-256color'
else
    export TERM='screen-256color'
fi


set -o vi
stty -ixon
alias cdm='cd ~/main'
alias ..='. ~/.bashrc'
alias o='thunar .'
export PATH=$PATH:$HOME/main/bin

# Quick way to go to "~/main/dev" folder
# Usage:
#   cdd
#   cdd my-project
function cdd() { cd ~/main/dev/"$@" ;}
function cde() { cd ~/main/env/"$@" ;}

function viman() { vim "+:Man $@" "+:only" ; }
